###############################################################################
#
#   Software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 06-03-2021
#   LICENSE: MIT
#
###############################################################################
---

name: tin

dependencies:
  - python=3.7.10
  - pip
  - pip:
    - -r file:requirements.txt

...
