## Set base image
FROM python:2.7.16

## Set metadata
LABEL base.image="python:2.7.16"
LABEL version="0.1.0"
LABEL software="tin_score_calculation"
LABEL software.version="0.1.0"
LABEL software.description="Given a set of BAM files and a gene annotation BED file, calculates the Transcript Integrity Number (TIN) for each transcript"
LABEL software.website="https://git.scicore.unibas.ch/zavolan_group/tools/tin_score_calculation"
LABEL software.documentation="https://git.scicore.unibas.ch/zavolan_group/tools/tin_score_calculation/blob/master/README.md"
LABEL software.license="https://git.scicore.unibas.ch/zavolan_group/tools/tin_score_calculation/blob/master/LICENSE"
LABEL software.tags="bioinformatics, quality control, rna-seq, bam, bed, tsv, transcript integrity"
LABEL maintainer="Mihaela Zavolan"
LABEL maintainer.email="mihaela.zavolan@unibas.ch"
LABEL maintainer.organisation="Zavolan lab, Biozentrum, University of Basel"

## Add system dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        libbz2-dev \
        liblzma-dev \
        zlib1g-dev && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

## Copy and install required packages
COPY ./requirements.txt /requirements/requirements.txt
RUN pip install -r /requirements/requirements.txt

## Copy script
COPY src/tin_score_calculation.py /bin/tin_score_calculation.py

