###############################################################################
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 05-03-2021
#
###############################################################################
---

name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - dev
      - master

jobs:

  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.10

      - name: Install the dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install .

      - name: Test --help param for the calculate-tin.py
        run: |
          calculate-tin.py --help 1> .test/calculate-tin/ci-help-stdout.txt
          cmp .test/calculate-tin/ci-help-stdout.txt .test/calculate-tin/help-stdout.txt

      - name: Test calculate-tin.py
        run: |
          calculate-tin.py -i .test/calculate-tin/sample.bam -r .test/calculate-tin/transcripts.bed --names "sample_name" 1> .test/calculate-tin/ci.tsv
          cmp .test/calculate-tin/ci.tsv .test/calculate-tin/sample.tsv

      - name: Test --help param for the merge-tin.py
        run: |
          merge-tin.py --help 1> .test/merge-tin/ci-help-stdout.txt
          cmp .test/merge-tin/ci-help-stdout.txt .test/merge-tin/help-stdout.txt

      - name: Test merge-tin.py
        run: |
          merge-tin.py --input-files .test/merge-tin/sample_1.tsv .test/merge-tin/sample_2.tsv --output-file .test/merge-tin/ci.tsv
          cmp .test/merge-tin/ci.tsv .test/merge-tin/merged.tsv

      - name: Test --help param for the plot-tin.py
        run: |
          plot-tin.py --help 1> .test/plot-tin/ci-help-stdout.txt
          cmp .test/plot-tin/ci-help-stdout.txt .test/plot-tin/help-stdout.txt

      - name: Test plot-tin.py
        run: |
          plot-tin.py --input-file .test/plot-tin/merged.tsv --output-file-prefix .test/plot-tin/ci
          # .pdf and png might differ so we cannot test

  linting:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install the dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user flake8==3.7.9

      - name: Static code analysis
        run: /home/runner/.local/bin/flake8 --max-line-length 120 scripts/

...
