name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - dev
      - master

jobs:

  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install the dependencies
        run: pip install -r requirements.txt
